"""relate customers to tickets

Revision ID: 42fdefad6d31
Revises: 03fc319c29e9
Create Date: 2024-12-15 07:43:38.754343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42fdefad6d31'
down_revision: Union[str, None] = '03fc319c29e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('customer_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'customer_id')
    # ### end Alembic commands ###
