"""relate users to tickets

Revision ID: 9ecd75dcfdbc
Revises: d37d6e7015df
Create Date: 2024-12-13 10:14:07.021432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ecd75dcfdbc'
down_revision: Union[str, None] = 'd37d6e7015df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'user_id')
    # ### end Alembic commands ###
