"""add password hash

Revision ID: cd748740368c
Revises: 6218501d4f9b
Create Date: 2024-12-12 07:37:35.348582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd748740368c'
down_revision: Union[str, None] = '6218501d4f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_email_key', 'customers', type_='unique')
    op.drop_column('customers', 'email')
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.add_column('customers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('customers_email_key', 'customers', ['email'])
    # ### end Alembic commands ###
